### ISSUE TITLE
Tracker update frequency

### ISSUE THREAD

**Issue by pwalsh** [okfn/ibp-explorer#85]
# User story

As an {Administrator}, I want the Tracker to take two updates a year instead of monthly updates as done until now, so that Tracker data is more relevant based on actual data changes.
## Notes
- To work, we need this data available from Indaba. If it is not available when work starts, delays in the timeline are to be expected.
- We need some example API queries, with actual data, to understand this.
# Tasks
- [x] Write standalone script that talks to the API, and creates a snapshot
  - What a snapshot looks like depends on what our current monthly snapshots look like - please advise if any problems
- [x] The script reads the API and saves the snapshot to a remote fileserver. We can use an S3 bucket for convenience
- [x] S3 bucket should have a naming convention that exposes a "snapshots API" for our code
- [x] Write the logic to display snapshots in the UI
- [ ] Write some unit tests

**Comment by pwalsh** [comment]
@dumyan 

this should be completely related to the static file snapshots included with the explorer codebase, as I understand it now, and not the Indaba code directly. I guess that the generate these snapshots we had some scripts that run against Aquarium to generate them? can you check?

**Comment by dumyan** [comment]
Not sure if that is the case. The explorer is updated by static files that are parsed locally, it doesn't communicate with any outside API. Also the request mentions that it was monthly update and now it should be semi-annually, so I would say this is related to the tracker because the tracker date is ticking forward monthly.

**Comment by pwalsh** [comment]
ok got it. 

can you change it to tick every 6 months, and this is completely related to https://github.com/okfn/open-budget-survey/issues/93 which is actually the implementation for this user story, so we should merge.

**Comment by pwalsh** [comment]
@dumyan 

- I removed some comments in this thread that were unrelated.
- I updated the tasks list
- I created an S3 bucket and shared shared in our slack channel

Can you please consider the above approach, and estimate time.

**Comment by pwalsh** [comment]
@dumyan we'll use cron or similar to run this snapshot script - it does not have to be integrated into the web app framework.

**Comment by dumyan** [comment]
I think 1.5d will be enough for this, more or less if there aren't any blockers around. I'm not sure if I get "Write the logic to display snapshots in the UI" right, this UI is the tracker, am I right?

**Comment by pwalsh** [comment]
@dumyan I think so - check where the current snapshots are used pls.
