### ISSUE TITLE
Wrap app in Node.js shell

### ISSUE THREAD

**Issue by pwalsh** [okfn/ibp-explorer#95]
# Description

We really need a server. Especially for things like https://github.com/okfn/ibp-explorer/issues/85 but also we have other env vars that would be much more manageable in a server.

We might also just pull out the tracker stuff and put it in this server, making the whole endeavour here more sane (but we'll consider that after we have a server).
# Tasks
- [x] Wrap this app in a simple node app
  - [x] Don't even touch routing or anything yet. Treat node more like a dumb host that provides an environment/context to a classic "frontend" app
  - [x] Move all env vars to  normal Node config, and expose the vars to the frontend app

Do not labour over anything here. We want this quick and simple for this first iteration. See some of our other Node apps for reference on our stack:
- https://github.com/frictionlessdata/data-quality-dashboard
  - [config](https://github.com/frictionlessdata/data-quality-dashboard/blob/master/app/config.js)
  - [server](https://github.com/frictionlessdata/data-quality-dashboard/blob/master/app/index.js)
  - [app conventions](https://github.com/frictionlessdata/data-quality-dashboard/blob/master/app/backend/index.js)
  - [entry point for ES6 code](https://github.com/frictionlessdata/data-quality-dashboard/blob/master/server.js)

**Comment by pwalsh** [comment]
DONE
